.TH PROMOE 1
.SH NAME
promoe \- gui client for xmms2
.SH SYNOPSIS
.B promoe
.P
.SH DESCRIPTION
.I Promoe
is a client for the xmms2 music daemon. Promoe's interface is modeled after
XMMS/WinAMP classic.
.SH FILES
.TP
.I $XDG_CONFIG_HOME/xmms2/Promoe.conf
The configuration file
.TP
.I $HOME/.config/xmms2/clients/promoe/skins
Default directory for skins, can be changed in the configuration file
.SH  ENVIRONMENT VARIABLES
.TP
.I XMMS_PATH
The URL path to
.I xmms2d.
See
.B IPC SOCKET
in
.I xmms2d(8)
for details of possible values for this variable
.SH SEE ALSO
xmms2d(8), http://xmms2.xmms.org
.SH BUGS
Please report bugs at 
.B http://bugs.xmms2.xmms.se
.SH AUTHORS
Thomas Frauendorfer, Tobias Rundström, Daniel Svensson and others.  
The
.B AUTHORS
file contains a complete list of contributors
.PP
Thomas Frauendorfer is to blame for the manpage
