# encoding: utf-8
# vim:set syntax=python expandtab :

"""
This file is a part of Promoe, an XMMS2 Client

Copyright (C) 2009 XMMS2 Team

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

3. The name of the author may not be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
"""

def set_options(opt):
    pass
def configure(conf):
    pass
def build(bld):
    obj              = bld.new_task_gen('qt4', 'cxx')
    obj.target       = 'promoe_data'
    obj.install_path = 0 # Don't install
    obj.source       = 'skins/Almond-blue.qrc'
    obj.uselib       = 'QTCORE'

    bld.install_files('${MANDIR}/man1', 'promoe.1')
    bld.install_files('${DATADIR}/applications', 'promoe.desktop')
    bld.install_files('${DATADIR}/icons', 'icons/ashton-flame1/promoe.svg')

